# Generated by Django 3.1.5 on 2021-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pic',
            field=models.FileField(upload_to='images'),
        ),
    ]
