# Generated by Django 3.1.5 on 2021-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20210131_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
