# Generated by Django 3.1.5 on 2021-01-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20210131_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
