# Generated by Django 3.1.5 on 2021-01-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final_app', '0004_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='image')),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
