# Generated by Django 3.1.5 on 2021-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_mygallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygallery',
            name='catagory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mygallery',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mygallery',
            name='pic',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
